version: "3.8"

services:
  docker-risa-playground:
    image: martokk/docker-risa-playground:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /workspace:/workspace
    ports:
      - "3000:3001"
      - "3010:3011"
      - "3020:3021"
      - "6006:6066"
      - "8888:8888"
      - "5001:5001"
    environment:
      JUPYTER_PASSWORD: "Jup1t3R!"
      START_A1111: "1"
      START_KOHYA: "1"
      START_COMFYUI: "1"
      START_INVOKEAI: "1"
      START_JUPYTER: "1"
      START_TENSORBOARD: "1"
      START_RISA_PLAYGROUND: "1"
      RISA_ENV_NAME: "playground"
      RISA_ACCESS_SECRET_KEY: "jwt-access-secret-key"
      RISA_REFRESH_SECRET_KEY: "jwt-refresh-secret-key"
      RISA_FIRST_SUPERUSER_EMAIL: "admin@example.com"
      RISA_FIRST_SUPERUSER_PASSWORD: "admin"
      RISA_FIRST_SUPERUSER_USERNAME: "admin"
      RISA_PROJECT_NAME: "Risa Playground"
      RISA_EXPORT_API_KEY: "secret-key-export-api"
    restart: unless-stopped
