# Example symlinks.yaml
#
# This file is used by the pre_start.sh script to create symlinks at container startup.
# Add entries here to link files or directories from a source to a destination.
#
# - source: /path/to/original/file
#   destination: /path/to/symlink

# DOCKER CONTAINER ---------------------------------------------------------------------------------------------

# A1111 --------------------------------------------------------------------------------------------------------
- source: /workspace/configs/a1111/config.json
  destination: /workspace/apps/stable-diffusion-webui/config.json

- source: /workspace/configs/a1111/ui-config.json
  destination: /workspace/apps/stable-diffusion-webui/ui-config.json

- source: /workspace/configs/a1111/styles.csv
  destination: /workspace/apps/stable-diffusion-webui/styles.csv

- source: /workspace/configs/a1111/webui-user.sh
  destination: /workspace/apps/stable-diffusion-webui/webui-user.sh

- source: /workspace/apps/stable-diffusion-webui/outputs
  destination: /workspace/__OUTPUTS__/a1111

# KOHYA_SS -----------------------------------------------------------------------------------------------------
- source: /workspace/configs/kohya_ss/.env
  destination: /workspace/apps/kohya_ss/.env

# KOHYA_SS PRESETS ---------------------------------------------------------------------------------------------
- source: "/workspace/configs/kohya_ss/presets/lora/vDefault - Lora - 1024x1024.json"
  destination: "/workspace/apps/kohya_ss/presets/lora/vDefault - Lora - 1024x1024.json"
# COMFYUI ------------------------------------------------------------------------------------------------------

# INVOKEAI ----------------------------------------------------------------------------------------------------

# RISA ---------------------------------------------------------------------------------------------------------

# WEBDAV ------------------------------------------------------------------------------------------------------

# HUB ----------------------------------------------------------------------------------------------------------
- source: /workspace/hub/models/SDXL/checkpoints/
  destination: /workspace/apps/stable-diffusion-webui/models/Stable-diffusion/

- source: /workspace/hub/models/SDXL/loras/
  destination: /workspace/apps/stable-diffusion-webui/models/Lora/

- source: /workspace/hub/models/SDXL/embeddings/
  destination: /workspace/apps/stable-diffusion-webui/embeddings
