name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add disk space cleanup step
      - name: Free disk space
        run: |
          echo "Initial disk space:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          echo "Disk space after cleanup:"
          df -h

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Add buildx configuration to clean up after each build
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:latest
            network=host
            env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
            env.BUILDKIT_STEP_LOG_MAX_SPEED=-1

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # The 'docker/build-push-action' step was replaced by a direct 'run' command
      # to work around an issue where the runner was not recognizing the 'bake' input.
      - name: Build and Push with docker-bake.hcl
        run: |
          docker buildx bake --file ./docker-bake.hcl default ${{ github.ref == 'refs/heads/main' && '--push' || '' }}

      - name: Create Deployment
        if: github.ref == 'refs/heads/main' && success()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: []
            })
