name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add disk space cleanup step
      - name: Free disk space
        run: |
          echo "Initial disk space:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache
          echo "Disk space after cleanup:"
          df -h

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          # Add buildx configuration to clean up after each build
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:latest
            network=host
            env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
            env.BUILDKIT_STEP_LOG_MAX_SPEED=-1

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build image and push to GitHub Container Registry
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     tags: |
      #       ghcr.io/martokk/server_status_api:latest
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # The existing 'docker buildx bake' run step is replaced by the action below
      - name: Build and Push with docker-bake.hcl
        id: bake # You can keep 'bake' or use another id like 'docker_build'
        uses: docker/build-push-action@v5 # Using a recent version of the action
        env:
          BUILDKIT_PROGRESS: plain # Ensures verbose build output similar to your run step
        with:
          bake: ./docker-bake.hcl
          targets: default # Explicitly specify the bake target(s) to build
          push: ${{ github.ref == 'refs/heads/main' }}
          # The action will build and cache on PRs (when push is false)
          # and build and push on merges to main (when push is true).

      - name: Create Deployment
        if: github.ref == 'refs/heads/main' && success()
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              auto_merge: false,
              required_contexts: []
            })
